apiVersion: v1
kind: Pod
metadata:
  name: sample-api
  namespace: default
spec:
  containers:
  - name: sample-api-container
    image: alexrudocker/sample-api-dynamodb:latest
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"

